### ISSUE TITLE
想请教一下如何增加或修改用于登陆系统的账号

### ISSUE THREAD

**Issue by Yazawa-Nico** [wdlhao/vue2-element-touzi-admin#16]
rt 如果想新增一个用于登陆系统的账号应该如何做呢 谢谢~

**Comment by wdlhao** [comment]
项目便于测试用户权限，只针对username为‘admin’或‘editor’进行登录；如果要新增用户，只需修改src/mockjs/user.js中，login接口和getUserInfo接口即可；
