### ISSUE TITLE
关于筛选的问题求教

### ISSUE THREAD

**Issue by YACC995** [wdlhao/vue2-element-touzi-admin#17]
在资金管理 ->资金流水页面中如果想通过用户名以外的字段进行筛选应该如何修改呢 比如改用籍贯筛选

**Comment by wdlhao** [comment]
1.在searchItem添加你的搜索项，如籍贯；
2.在mockjs/money.js中，getMoneyList方法中，添加逻辑判断，返回符合多项搜索条件的数据；即可；

**Comment by YACC995** [comment]
好的 非常感谢~
