### ISSUE TITLE
左侧menu栏太长，不能下拉

### ISSUE THREAD

**Issue by webthen** [wdlhao/vue2-element-touzi-admin#2]
点击金融管理，再点击文章管理，发现左侧菜单栏不能滚动。

**Comment by wzhz** [comment]
我也发现了这个问题，[http://www.jiouai.com/](http://www.jiouai.com/)

框架是element-ui，之前我用的其他框架没有这个问题

**Comment by wdlhao** [comment]
请用维护分支dev-permission,纯前端项目，已经修复左侧菜单栏不能滚动。
