### ISSUE TITLE
dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗

### ISSUE THREAD

**Issue by wei1102816471** [wdlhao/vue2-element-touzi-admin#21]

**Comment by wdlhao** [comment]
前端直接运行，通过路由默认定位到登录页面；

**Comment by wei1102816471** [comment]
成功跳转登录界面，不知道账号密码登录不进，不是dev分支不需要本地安装和启动后台服务器的吗



------------------ 原始邮件 ------------------
发件人: "xiaolin"<notifications@github.com>; 
发送时间: 2019年9月26日(星期四) 上午8:58
收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>; 
抄送: "Winter is Coming"<1102816471@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21)




前端直接运行，通过路由默认定位到登录页面；

**Comment by wdlhao** [comment]
------------------
 目前正在维护的分支为dev-permission,其他分支暂不维护； 






------------------ 原始邮件 ------------------
发件人: "wei1102816471"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 上午9:00
收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>;
抄送: "酷酷の林"<906144643@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21)



成功跳转登录界面，不知道账号密码登录不进，不是dev分支不需要本地安装和启动后台服务器的吗 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "xiaolin"<notifications@github.com>;  
 发送时间: 2019年9月26日(星期四) 上午8:58 
 收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>;  
 抄送: "Winter is Coming"<1102816471@qq.com>; "Author"<author@noreply.github.com>;  
 主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21) 
 
 
 
 
 前端直接运行，通过路由默认定位到登录页面；

**Comment by wei1102816471** [comment]
dev-permission我也拉取了，但我想问下这个项目配置了webpack的吗


------------------ 原始邮件 ------------------
发件人: "xiaolin"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 上午9:07
收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>;
抄送: "Winter is Coming"<1102816471@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21)



------------------ 
  目前正在维护的分支为dev-permission,其他分支暂不维护；  
 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "wei1102816471"<notifications@github.com>; 
 发送时间: 2019年9月26日(星期四) 上午9:00 
 收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>; 
 抄送: "酷酷の林"<906144643@qq.com>;"State change"<state_change@noreply.github.com>; 
 主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21) 
 
 
 
 成功跳转登录界面，不知道账号密码登录不进，不是dev分支不需要本地安装和启动后台服务器的吗  
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "xiaolin"<notifications@github.com>;   
  发送时间: 2019年9月26日(星期四) 上午8:58  
  收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>;   
  抄送: "Winter is Coming"<1102816471@qq.com>; "Author"<author@noreply.github.com>;   
  主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21)  
   
   
   
   
  前端直接运行，通过路由默认定位到登录页面；

**Comment by wdlhao** [comment]
dev-permission分支，使用vue-cli3.0搭建，自带webpack配置；
------------------
 


 




------------------ 原始邮件 ------------------
发件人: "wei1102816471"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 上午9:10
收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>;
抄送: "酷酷の林"<906144643@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21)



dev-permission我也拉取了，但我想问下这个项目配置了webpack的吗 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "xiaolin"<notifications@github.com>; 
 发送时间: 2019年9月26日(星期四) 上午9:07 
 收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>; 
 抄送: "Winter is Coming"<1102816471@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21) 
 
 
 
 ------------------  
   目前正在维护的分支为dev-permission,其他分支暂不维护；   
   
   
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "wei1102816471"<notifications@github.com>;  
  发送时间: 2019年9月26日(星期四) 上午9:00  
  收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>;  
  抄送: "酷酷の林"<906144643@qq.com>;"State change"<state_change@noreply.github.com>;  
  主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21)  
   
   
   
  成功跳转登录界面，不知道账号密码登录不进，不是dev分支不需要本地安装和启动后台服务器的吗   
     
     
     
   ------------------ 原始邮件 ------------------   
   发件人: "xiaolin"<notifications@github.com>;    
   发送时间: 2019年9月26日(星期四) 上午8:58   
   收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>;    
   抄送: "Winter is Coming"<1102816471@qq.com>; "Author"<author@noreply.github.com>;    
   主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21)   
     
     
     
     
   前端直接运行，通过路由默认定位到登录页面；

**Comment by wei1102816471** [comment]
嗯，我看有些项目没有build的文件夹只有个vue.config.js，所以想问下dev-permission分支下的vue.config.js这个文件已经满足打包的配置了是吗，感谢


------------------ 原始邮件 ------------------
发件人: "xiaolin"<notifications@github.com>;
发送时间: 2019年9月26日(星期四) 上午9:12
收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>;
抄送: "Winter is Coming"<1102816471@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21)



dev-permission分支，使用vue-cli3.0搭建，自带webpack配置； 
 ------------------ 
   
 
 
   
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "wei1102816471"<notifications@github.com>; 
 发送时间: 2019年9月26日(星期四) 上午9:10 
 收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>; 
 抄送: "酷酷の林"<906144643@qq.com>;"State change"<state_change@noreply.github.com>; 
 主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21) 
 
 
 
 dev-permission我也拉取了，但我想问下这个项目配置了webpack的吗  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "xiaolin"<notifications@github.com>;  
  发送时间: 2019年9月26日(星期四) 上午9:07  
  收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>;  
  抄送: "Winter is Coming"<1102816471@qq.com>;"Author"<author@noreply.github.com>;  
  主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21)  
   
   
   
  ------------------   
    目前正在维护的分支为dev-permission,其他分支暂不维护；    
     
     
     
     
     
     
   ------------------ 原始邮件 ------------------   
   发件人: "wei1102816471"<notifications@github.com>;   
   发送时间: 2019年9月26日(星期四) 上午9:00   
   收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>;   
   抄送: "酷酷の林"<906144643@qq.com>;"State change"<state_change@noreply.github.com>;   
   主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21)   
     
     
     
   成功跳转登录界面，不知道账号密码登录不进，不是dev分支不需要本地安装和启动后台服务器的吗    
       
       
       
    ------------------ 原始邮件 ------------------    
    发件人: "xiaolin"<notifications@github.com>;     
    发送时间: 2019年9月26日(星期四) 上午8:58    
    收件人: "wdlhao/vue2-element-touzi-admin"<vue2-element-touzi-admin@noreply.github.com>;     
    抄送: "Winter is Coming"<1102816471@qq.com>; "Author"<author@noreply.github.com>;     
    主题: Re: [wdlhao/vue2-element-touzi-admin] dev分支拉取下来为什么要登录验证？不是前端可以直接运行的吗 (#21)    
       
       
       
       
    前端直接运行，通过路由默认定位到登录页面；
