### ISSUE TITLE
安装npm时报错

### ISSUE THREAD

**Issue by jessyzhang** [wdlhao/vue2-element-touzi-admin#6]
请问下这个问题该怎么解决呢?
具体报错信息:
 tarball tarball data for echarts@3.6.2 (sha1-hilUyLWBC/+HpIsN4EFu2MS7HDY=) seems to be corrupted. Trying one more time.
安装过程中所有模块都存在了.staging文件夹中，但是安装失败后， .staging内文件都被删除了。
尝试过npm cache verify和npm update， 但不生效。
版本信息
npm@6.4.1
node@10.14.2
操作系统: win10(x64)

**Comment by wdlhao** [comment]
请用最新的维护分支dev-permission,拉取代码，安装依赖，试下；
